global:
  scrape_interval: 2s 
scrape_configs:
  - job_name: 'clicker-game'
    static_configs:
      - targets: ['app:5000']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']